version: '3'

services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html

  mariadb:
    image: mariadb:10.3
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: qwerty
    depends_on:
      - mariadb
